### boats index
GET http://localhost:3000/boats

### boat create
POST http://localhost:3000/boats
Content-Type: application/json

{
  "brand": "Seadoo",
  "length": "12 ft",
  "price": 9000
}

### boat show
GET http://localhost:3000/boats/2